package nl.pindab0ter.aoc2025.day07

import nl.pindab0ter.lib.toGrid
import org.junit.jupiter.api.DisplayName
import kotlin.test.Test
import kotlin.test.assertEquals

@DisplayName("2025 Day 07 - Laboratories")
class LaboratoriesKtTest {
    @Test
    fun `Part one`() {
        val actual = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """
            .trimIndent()
            .lines()
            .simulateTachyonBeamSplitting()
            .count

        assertEquals(21, actual)
    }

    @Test
    fun `Part two`() {
        val actual = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """
            .trimIndent()
            .toGrid()
            .countPossibleTrajectories()

        assertEquals(40uL, actual)
    }
}
